<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FastEndpoints.Security" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KlinikGigiV2.Core\KlinikGigiV2.Core.csproj" />
    <ProjectReference Include="..\KlinikGigiV2.SharedKernel\KlinikGigiV2.SharedKernel.csproj" />
  </ItemGroup>

</Project>
