// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from '@pinia/colada';

import { klinikGigiV2WebUsersCreateCreate, type Options } from '../sdk.gen';
import type { KlinikGigiV2WebUsersCreateCreateData, KlinikGigiV2WebUsersCreateCreateResponse } from '../types.gen';

export const klinikGigiV2WebUsersCreateCreateMutation = (options?: Partial<Options<KlinikGigiV2WebUsersCreateCreateData>>): UseMutationOptions<KlinikGigiV2WebUsersCreateCreateResponse, Options<KlinikGigiV2WebUsersCreateCreateData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await klinikGigiV2WebUsersCreateCreate({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
