// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:57679' | (string & {});
};

export type CreateUserResponse = GenericResponse & {
    user?: UserRecord | null;
};

export type UserRecord = {
    id?: string;
    email?: string | null;
    role?: string | null;
    fullName?: string | null;
    createdAt?: string;
    updatedAt?: string;
};

export type GenericResponse = {
    message?: string;
    error?: unknown;
};

export type CreateUserRequest = {
    fullName?: string;
    email?: string;
    passwordHash?: string;
};

export type KlinikGigiV2WebUsersCreateCreateData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/klinik/users';
};

export type KlinikGigiV2WebUsersCreateCreateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type KlinikGigiV2WebUsersCreateCreateResponses = {
    /**
     * Success
     */
    200: CreateUserResponse;
};

export type KlinikGigiV2WebUsersCreateCreateResponse = KlinikGigiV2WebUsersCreateCreateResponses[keyof KlinikGigiV2WebUsersCreateCreateResponses];
